2017-01-16 17:37:22+0000 [-] Log opened.
2017-01-16 17:37:22+0000 [-] KademliaProtocol starting on 8468
2017-01-16 17:37:22+0000 [NodeSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:37:22+0000 [NodeSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:37:22+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:37:22+0000 [-] Unhandled error in Deferred:
2017-01-16 17:37:22+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 1030, in _cbDeferred
	    self.callback(self.resultList)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 457, in callback
	    self._startRunCallbacks(result)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	exceptions.TypeError: done() takes exactly 1 argument (2 given)
	
2017-01-16 17:39:05+0000 [-] Received SIGINT, shutting down.
2017-01-16 17:39:05+0000 [__main__.EchoFactory] (TCP Port 8007 Closed)
2017-01-16 17:39:05+0000 [-] Stopping factory <__main__.EchoFactory instance at 0x10a41e758>
2017-01-16 17:39:05+0000 [KademliaProtocol (UDP)] (UDP Port 8468 Closed)
2017-01-16 17:39:05+0000 [-] Main loop terminated.
2017-01-16 17:39:06+0000 [-] Log opened.
2017-01-16 17:39:06+0000 [-] KademliaProtocol starting on 8468
2017-01-16 17:39:06+0000 [NodeSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:39:06+0000 [NodeSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:39:06+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:39:06+0000 [-] Unhandled error in Deferred:
2017-01-16 17:39:06+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 1030, in _cbDeferred
	    self.callback(self.resultList)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 457, in callback
	    self._startRunCallbacks(result)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	exceptions.TypeError: done() takes exactly 1 argument (2 given)
	
2017-01-16 17:39:55+0000 [-] Received SIGINT, shutting down.
2017-01-16 17:39:55+0000 [__main__.EchoFactory] (TCP Port 8007 Closed)
2017-01-16 17:39:55+0000 [-] Stopping factory <__main__.EchoFactory instance at 0x108bf2248>
2017-01-16 17:39:55+0000 [KademliaProtocol (UDP)] (UDP Port 8468 Closed)
2017-01-16 17:39:55+0000 [-] Main loop terminated.
2017-01-16 17:41:20+0000 [-] Log opened.
2017-01-16 17:41:20+0000 [-] KademliaProtocol starting on 8468
2017-01-16 17:41:20+0000 [NodeSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:41:20+0000 [NodeSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:41:20+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:41:20+0000 [KademliaProtocol (UDP)] Found nodes: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:41:20+0000 [-] Unhandled error in Deferred:
2017-01-16 17:41:20+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 1030, in _cbDeferred
	    self.callback(self.resultList)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 457, in callback
	    self._startRunCallbacks(result)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/henrymortimer/Projects/finalYearProject/p2ppki/dhtServer.py", line 21, in done
	    self.readyCallback(self)
	exceptions.TypeError: ready() takes exactly 1 argument (2 given)
	
2017-01-16 17:41:26+0000 [-] Received SIGINT, shutting down.
2017-01-16 17:41:26+0000 [__main__.EchoFactory] (TCP Port 8007 Closed)
2017-01-16 17:41:26+0000 [-] Stopping factory <__main__.EchoFactory instance at 0x10b249680>
2017-01-16 17:41:26+0000 [KademliaProtocol (UDP)] (UDP Port 8468 Closed)
2017-01-16 17:41:26+0000 [-] Main loop terminated.
2017-01-16 17:42:55+0000 [-] Log opened.
2017-01-16 17:42:55+0000 [-] KademliaProtocol starting on 8468
2017-01-16 17:42:55+0000 [NodeSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:42:55+0000 [NodeSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:42:55+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:42:55+0000 [KademliaProtocol (UDP)] Found nodes: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:42:55+0000 [Server] [DEBUG] setting 'a key' = 'a value' on network
2017-01-16 17:42:55+0000 [NodeSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:42:55+0000 [NodeSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:42:55+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:42:55+0000 [Server] [INFO] setting 'a key' on ['192.168.62.128:8468']
2017-01-16 17:42:55+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:42:55+0000 [-] Unhandled error in Deferred:
2017-01-16 17:42:55+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 1030, in _cbDeferred
	    self.callback(self.resultList)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 457, in callback
	    self._startRunCallbacks(result)
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Users/henrymortimer/Projects/finalYearProject/ENV/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	exceptions.TypeError: getValue() takes exactly 2 arguments (3 given)
	
2017-01-16 17:43:01+0000 [-] Received SIGINT, shutting down.
2017-01-16 17:43:01+0000 [KademliaProtocol (UDP)] (UDP Port 8468 Closed)
2017-01-16 17:43:01+0000 [__main__.EchoFactory] (TCP Port 8007 Closed)
2017-01-16 17:43:01+0000 [-] Stopping factory <__main__.EchoFactory instance at 0x10c0ac758>
2017-01-16 17:43:01+0000 [-] Main loop terminated.
2017-01-16 17:45:44+0000 [-] Log opened.
2017-01-16 17:45:44+0000 [-] KademliaProtocol starting on 8468
2017-01-16 17:45:44+0000 [NodeSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:45:44+0000 [NodeSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:45:44+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:45:44+0000 [KademliaProtocol (UDP)] Found nodes: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:45:44+0000 [Server] [DEBUG] setting 'a key' = 'a value' on network
2017-01-16 17:45:44+0000 [NodeSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:45:44+0000 [NodeSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:45:44+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:45:44+0000 [Server] [INFO] setting 'a key' on ['192.168.62.128:8468']
2017-01-16 17:45:44+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:45:44+0000 [ValueSpiderCrawl] [INFO] creating spider with peers: [[1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468]]
2017-01-16 17:45:44+0000 [ValueSpiderCrawl] [INFO] crawling with nearest: ([1418938165641541645363477400294636438323052247203L, '192.168.62.128', 8468],)
2017-01-16 17:45:44+0000 [KademliaProtocol] [INFO] got response from 192.168.62.128:8468, adding to router
2017-01-16 17:45:50+0000 [-] Received SIGINT, shutting down.
2017-01-16 17:45:50+0000 [KademliaProtocol (UDP)] (UDP Port 8468 Closed)
2017-01-16 17:45:50+0000 [__main__.EchoFactory] (TCP Port 8007 Closed)
2017-01-16 17:45:50+0000 [-] Stopping factory <__main__.EchoFactory instance at 0x10dd432d8>
2017-01-16 17:45:50+0000 [-] Main loop terminated.
